# Generated by Django 4.2.6 on 2023-12-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_rename_amount_bordereauop_post_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bordereauop',
            old_name='credit',
            new_name='CREDIT',
        ),
        migrations.RenameField(
            model_name='bordereauop',
            old_name='debit',
            new_name='DEBIT',
        ),
        migrations.RenameField(
            model_name='bordereauop',
            old_name='fees',
            new_name='FEES',
        ),
        migrations.RenameField(
            model_name='bordereauop',
            old_name='msisdn',
            new_name='MSISDN',
        ),
    ]
