# Generated by Django 4.2.6 on 2023-12-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_rename_credit_bordereauop_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauop',
            name='TRANSFER_DATE',
            field=models.DateTimeField(null=True),
        ),
    ]
