# Generated by Django 4.2.6 on 2023-12-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_alter_bordereauop_previous_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauop',
            name='PREVIOUS_BALANCE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bordereauop',
            name='TRANSFER_DATE',
            field=models.DateTimeField(default=''),
        ),
    ]
