# Generated by Django 4.2.6 on 2023-12-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0012_alter_bordereauop_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauop',
            name='TRANSFER_DATE',
            field=models.DateTimeField(),
        ),
    ]
