# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "serverWeb" do |serverWeb|
    serverWeb.vm.box = "ubuntu/bionic64"
    serverWeb.vm.network "private_network", ip: "192.168.1.4"
    serverWeb.vm.network "forwarded_port", guest: 8085, host: 8084
    serverWeb.vm.hostname = "serverWeb"
    serverWeb.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
	serverWeb.vm.boot_timeout = 600
    end
	 serverWeb.vm.synced_folder "C:/ProjetVirtualisation/vagrantProjet/serverWeb/vagrantFront/target", "/vagrant/target", create: true, type: "rsync"
    serverWeb.vm.provision "shell", path: "script/webserver.sh"
  end
end


