# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.define "serverApp" do |serverApp|
		serverApp.vm.box = "ubuntu/bionic64"
		serverApp.vm.network "private_network", ip: "192.168.1.3"
		serverApp.vm.network "forwarded_port", guest: 8082, host: 9090
		serverApp.vm.hostname = "serverApp"
		serverApp.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		end
		serverApp.vm.synced_folder "./vagrantApi", "/home/vagrant/vagrantApi", create: true, type: "rsync"
		serverApp.vm.provision "shell", path: "script/appserver.sh"
	end
end